### ISSUE TITLE
[wifi-login-app] Reusable auth token validation logic

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-wifi-login-pages#100]
As the application increase in complexity and identity verification methods are added like the one in #92, we need to check if the user is authenticated and allowed to see a specific page more often. Right now, some of this logic has been duplicated in #92 and is a bit cumbersome to manage, for this reason I started to think about a possible generic and reusable solutions for the current and future use cases.

A possible reusable `validateToken` function would work this way:

- if no auth token found in cookies, clear any session storage and return false
- if auth token in cookies and was not validated yet, proceed with validation
  - if validation fails, logout, ensure cookies and session storage are cleared, return false
  - if validation succeeds, store the returned data in a general state (redux?), possibly save it into sessionStorage to avoid repeating the operation if the user reloads the page, return true
- if token was already validated and previously fetched data, return true

### User data

Data which will be returned from the [openwisp-radius](https://openwisp-radius.readthedocs.io/en/latest/) API after successful validation:

- username
- email
- phone number
- is_active
- verification_method (this still needs to be defined/added)
- radius_token

### Flow

The logic to show a page only if user is authenticated/unauthenticated or to redirect to another page right now  flow is defined in the `OrganizationWrapper` component, but this splits the logic in two parts, on one side we have the actual component, on the other side we have `OrganizationWrapper` which knows when to display the page and when to redirect or perform a different action, I think this makes things more complicated: harder to debug and automatically test.
I think we aim to make `OrganizationWrapper` a simple list of routes and define the flows in the component themselves.

We should then find a way that would allow us to define the following flow, with less repetition and boilerplate as possible:

- **Login**
  - if authenticated: go to status
  - if not authenticated: show
- **Status**
  - if authenticated and active: show
  - if authenticated and inactive: redirect to identity verification (eg: mobile phone verification)
  - if not authenticated: go to login
- **Sign up**
  - if authenticated: go to status
  - if not authenticated: show
- **Verify Mobile Phone**
  - if not authenticated: go to login
  - if authenticated and active: go to status
  - if authenticated and not active and verification method is mobile phone: show
  - if authenticated and not active and verification method is not mobile phone: go to correct verification method component
- **Change Phone Number**
  - if authenticated: show
  - if not authenticated: go to login
- **Change Password**
  - if authenticated: show
  - if not authenticated: go to login
- **Reset password**
  - if authenticated: status
  - if not authenticated: show

**Comment by frappelatte28** [comment]
Hi @nemesisdesign Can I get some help here, I think it's an interesting problem. And I would really love to help.
