### ISSUE TITLE
[wifi-login-pages] Feature: show user details in status page

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-wifi-login-pages#104]
In the status page, we need to show the details of the currently logged in user:

- username (only if different than email and phone number)
- email
- phone number (if mobile phone verification enabled)

**Comment by NoumbissiValere** [comment]
>     * username (only if different than email and phone number)

only if different than email and `phone number`? should phone number be part of this statement?

**Comment by nemesisdesign** [comment]
> > ```
> > * username (only if different than email and phone number)
> > ```
> 
> only if different than email and `phone number`? should phone number be part of this statement?

Maybe you can skip comparing username to phone number for now.
