### ISSUE TITLE
[CI] Move CI to github actions

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-wifi-login-pages#153]
Move CI to github actions.

**Comment by sankha555** [comment]
I had read upon Github actions a few weeks back. I'll try to make a patch for this.

**Comment by devkapilbansal** [comment]
@sankha555 are you working on this?

**Comment by sankha555** [comment]
I am not able to contribute currently, it can please be assigned to someone else. Sorry for the inconvenience.

**Comment by codesankalp** [comment]
Can I work on this issue? @nemesisdesign @devkapilbansal

**Comment by nemesisdesign** [comment]
Whoever wants to work on this, please go ahead and create a PR without asking for permission.
