### ISSUE TITLE
[wifi-login-pages] Ensure something is shown while page loads

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-wifi-login-pages#156]
I've been testing the app in a real public wifi environment and when the page is loaded in the mini-browser of  android or ubuntu it takes too many seconds to show something, during the loading the page is completely blank.

We must make sure a basic layout with a text that explains the page is loading is shown to the user.
This basic layout can be built in the main HTML file, without relying on external files (we can use the `<style>` tag for CSS).

**Update**: I think we should simply show the loading indicator, embedding it in public/index.html with inline code.
We shouldn't use words because the pages can be displayed in multiple languages and we have no way of translating the word in HTML without loading JS, therefore we should resort to something visual only.

**Comment by arkumari2000** [comment]
I would like to give it a try to this issue.

**Comment by nemesisdesign** [comment]
> I would like to give it a try to this issue.

Go for it. :+1:

**Comment by ishansinghal9810** [comment]
If the issue is still open i would love to contribute

**Comment by nemesisdesign** [comment]
@ishansinghal9810 yes it's still open.

**Update**: I think we should simply show the loading indicator, embedding it in public/index.html with inline code.
We shouldn't use words because the pages can be displayed in multiple languages and we have no way of translating the word in HTML without loading JS, therefore we should resort to something visual only.

**Comment by vivek-30** [comment]
@nemesisdesign, sir can i work on this issue?

**Comment by nemesisdesign** [comment]
@vivek-30 go for it :+1:

**Comment by vivek-30** [comment]
@nemesisdesign please have a look at #166

**Comment by ishansinghal9810** [comment]
maybe @vivek-30 have completed
