### ISSUE TITLE
[bug] Fix unique key props error when no links

### ISSUE THREAD

**Issue by niteshsinha17** [openwisp/openwisp-wifi-login-pages#169]
Whenever there is no link present in the footer unique key props error is shown in the browser console.

**Comment by Hanaffi** [comment]
@NoumbissiValere @niteshsinha17 @nemesisdesign 
Can you assign this to me please?

**Comment by niteshsinha17** [comment]
@Hanaffi dont worry about getting assigned. As you have commented first you can start working on it and create PR when you are done.

**Comment by Hanaffi** [comment]
@niteshsinha17 
Whenever I try to run `npm start`
I get that error:

This site can’t be reachedThe webpage at http://0.0.0.0:8080/ might be temporarily down or it may have moved permanently to a new web address.
ERR_ADDRESS_INVALID

**Comment by niteshsinha17** [comment]
Have you installed Openwisp radius?

**Comment by Hanaffi** [comment]
@niteshsinha17 Nope, Whats that?

**Comment by niteshsinha17** [comment]
You can assume it is used as a backend for openwisp-wifi-login-pages.
Please read [this](https://github.com/openwisp/openwisp-wifi-login-pages#install)  for more information.

**Comment by s0mnaths** [comment]
Please, can I try to work on this issue? @niteshsinha17 @nemesisdesign

**Comment by Purhan** [comment]
@niteshsinha17 @frappelatte28 @s0mnaths Are the pull requests https://github.com/openwisp/openwisp-wifi-login-pages/pull/181 and https://github.com/openwisp/openwisp-wifi-login-pages/pull/184/ both for the same bug? Or is it one bug occurring in different places?

**Comment by s0mnaths** [comment]
> @niteshsinha17 @frappelatte28 @s0mnaths Are the pull requests #181 and #184 both for the same bug? Or is it one bug occurring in different places?

It's for a different bug. Changes are in different files.

**Comment by s0mnaths** [comment]
> @niteshsinha17 @frappelatte28 @s0mnaths Are the pull requests #181 and #184 both for the same bug? Or is it one bug occurring in different places?

It is one bug occurring in different places I think. One is in the footer.js file and the other was in status.js

**Comment by frappelatte28** [comment]
> > @niteshsinha17 @frappelatte28 @s0mnaths Are the pull requests #181 and #184 both for the same bug? Or is it one bug occurring in different places?
> 
> It is one bug occurring in different places I think. One is in the footer.js file and the other was in status.js

Yeah, that's right.
