### ISSUE TITLE
[wifi-login-pages] Logout without breaking auto-login

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-wifi-login-pages#171]
To be done after #63.

When a user logs out, once they go back to the log in page, they will not be auto logged in if they enabled the remember me checkbox.

We need to find a way to make the auto-login feature work when the remember-me checkbox is enabled, so that when they connect to the WiFi again, they'll be automatically logged in when they open the page.

Right now users get automatically logged in only if they did not click the logout button.

The problem is that right now if one clicks logout, they're taken back to the login page, and without clearing the cookie session, they would be immediately logged in again.

So we could implement something like the following:

- if the remember me checkbox is enabled and the user logs out, ask them (with a modal message) if they want to be automatically logged in the next time they open the wifi
- if they choose no, the behavior is unchanged
- if they choose yes, the cookie/session data is not erased, but the captive portal log out is performed normally
- once the log out is performed, instead of taking back the user to the log in page, we direct them at a new page or a screen in the same status page, which communicates the successful log out and shows a button that says "Log in again" or something similar, which links the log in page

**Comment by jalajcodes** [comment]
I'd like to work on this issue.

**Comment by codesankalp** [comment]
I can work on this.

**Comment by codesankalp** [comment]
@nemesisdesign Since I have made a PR for [this](https://github.com/openwisp/openwisp-wifi-login-pages/issues/63).
Can I start working on this issue?

**Comment by nemesisdesign** [comment]
@codesankalp yes sure, is the problem clear?

**Comment by codesankalp** [comment]
> @codesankalp yes sure, is the problem clear?

Yes, I think so. If I will face any problem related to implementation I will ask it here.
