### ISSUE TITLE
[wifi-login-pages] Change: add support for new is_verified field

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-wifi-login-pages#172]
In the SMS verification flow, right now we check the `is_active` field to know if we should send the user to verify their phone number.

We have to switch to the new `is_verified` field once https://github.com/openwisp/openwisp-radius/issues/233 is completed, because `is_active` can be used also to ban users.

**Comment by pranavich18** [comment]
@nemesisdesign I would like to work on this issue.

**Comment by Purhan** [comment]
@pranavich18 this feature is not yet implemented and is in progress https://github.com/openwisp/openwisp-radius/pull/237
Please feel free to help test it or take up another issue.

**Comment by pranavich18** [comment]
Yeah but can I add is_verified field in the props for mobile-verification and open a PR so that  as soon as https://github.com/openwisp/openwisp-radius/pull/237 this is completed my PR can be merged??

**Comment by nemesisdesign** [comment]
https://github.com/openwisp/openwisp-radius/issues/233 is almost solved, so this one will be tackled next!

**Comment by codesankalp** [comment]
I have started working on this.
