### ISSUE TITLE
[bug] Fix unique key props error caused due to status Component

### ISSUE THREAD

**Issue by niteshsinha17** [openwisp/openwisp-wifi-login-pages#182]
Check console after login you will find unique key props error

**Comment by frappelatte28** [comment]
Hey @niteshsinha17 I want to work on this issue and this will be my first issue. Please can you help me with this? I saw the status component and statusTest.js file but could not find the key which is causing this error.

**Comment by niteshsinha17** [comment]
Sure, 
I think error is causing these lines of code. https://github.com/openwisp/openwisp-wifi-login-pages/blob/c27bf4d75c5b5d1ca8ab5e5e90be683736034970/client/components/status/status.js#L537-L549

**Comment by frappelatte28** [comment]
Hey @niteshsinha17 I was trying to solve the issue. For the current situation, the key is same for multiple renders for a link component which should be not the problem wrt react reconciliation mechanism. 
But I tried to solve this issue using react-uuid module which solved the problem as it is assigning different keys for each render which is costly. 
What do you think what should we do?
