### ISSUE TITLE
[docs] Refer to openwisp-radius Social Login configuration from README

### ISSUE THREAD

**Issue by frappelatte28** [openwisp/openwisp-wifi-login-pages#185]
To reproduce the bug run openwisp-wifi-login-page and try to login with either Facebook or Google.

@nemesisdesign @niteshsinha17 Can I start working on it?

**Comment by Purhan** [comment]
@frappelatte28 Did you configure social login in the backend? https://openwisp-radius.readthedocs.io/en/latest/user/social_login.html

**Comment by frappelatte28** [comment]
I am sorry, I missed this social login part. Thank you @Purhan!

**Comment by nemesisdesign** [comment]
I think we need to add a mention of this in the README, so I'll rename the issue.

**Comment by frappelatte28** [comment]
@nemesisdesign can I create a PR?

**Comment by frappelatte28** [comment]
Hey @nemesisdesign!

#### Setup

##### Add Organization configuration

Before users can login and sign up, you need to create the configuration of the
captive page for the related OpenWISP organization,
you should have noted down the parameters performed during the
[Installation of OpenWISP RADIUS ](#install-openwisp-radius), then you can run:


We already have this part in our readme file, do we need to add this `Configure Social Login` part specifically?

**Comment by codesankalp** [comment]
Yes, @frappelatte28 You need to add a reference to this https://openwisp-radius.readthedocs.io/en/latest/user/social_login.html in README.

**Comment by nemesisdesign** [comment]
@frappelatte28 thanks for the question, you can add it at the end, before LICENSE.

**Comment by frappelatte28** [comment]
@nemesisdesign I have made the requested changes, please review it!
