### ISSUE TITLE
[QA] Fix Coveralls to upload coverage

### ISSUE THREAD

**Issue by codesankalp** [openwisp/openwisp-wifi-login-pages#188]
CI build of PR shows that coveralls is not working fine.

![image](https://user-images.githubusercontent.com/56037184/111880412-74761d00-89d1-11eb-93b7-de8294503474.png)

**Comment by codesankalp** [comment]
@nemesisdesign Is this a valid issue?
If it is I will make a PR to fix this.

**Comment by devkapilbansal** [comment]
Yes, @codesankalp this seems to be a valid issue. 

> If it is I will make a PR to fix this.
Go ahead
