### ISSUE TITLE
[bug] Validate token endpoint being called unnecessarily

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-wifi-login-pages#217]
When logging in on the current master branch, I see that the endpoint which validates the user auth token is called 3 times:

![Screenshot from 2021-05-03 20-18-47](https://user-images.githubusercontent.com/841044/116951225-e4242c80-ac4c-11eb-8c5a-9e60521b1eec.png)

I am not sure why this is happening but it looks wrong to me.

Moreover, since I am logging in, I am just getting the token from the API so it should not be validated.

We have to ensure the following:

- whatever data which is got after validating the token can be sent also when the token is received after first authentication, so we can avoid having to call validate
- the validate token endpoint should be used only when the user is being recognized from an existing session or an older session and should be only called once

I think this is related to #100.

**Comment by codesankalp** [comment]
Oh, I observed it called three times in mobile verification.
