### ISSUE TITLE
[docs] Setup instructions in README

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-wifi-login-pages#22]
Could you expand the setup instructions so to have a series of commands that need to be run in order to run the application locally?

I understand that for you is obvious but for someone else may not.

Eg:

```
yarn
npm run build
npm run server
npm run client  # is this needed?
```

**Comment by TheOneAboveAllTitan** [comment]
Are present docs suitable? If you still suggest changes, I'll be happy to take up this job.

**Comment by nemesisdesign** [comment]
@Vivekrajput20 is this issue still relevant or can it be closed?
