### ISSUE TITLE
[bug] Change phone number is broken after introduction of remember me checkbox

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-wifi-login-pages#231]
**How to replicate**:

- create user with mobile verification turned on
- verify mobile number
- go to change mobile phone
- change phone number and submit

**Expected result**:

- verification process starts again

**Actual result**:

- invalid token

**Analysis**:

The token variable received by the controller is `undefined`.
This started to happen after merging 54bbfbfd6bded98f60cdb8340bc7fd15d0db110e (https://github.com/openwisp/openwisp-wifi-login-pages/pull/186).

If one tries to go back to the repository at the state where it was before that commit, the functionality works normally.

While reviewing those changes again, I found out that some parts of the code need more explanation on what is being done to make it clearer.

Please @codesankalp can you help out with this?

**Comment by codesankalp** [comment]
I solved the token issue. But I noticed another bug which is before the commit of the remember-me checkbox i.e. after changing the phone number it sends the verification code but the verification page opens for a very few seconds and then the user Is being redirected to the status page. 
Should I fix this in this issue or create a new one? @nemesisdesign
