### ISSUE TITLE
[feature] Implement get text like translations

### ISSUE THREAD

**Issue by codesankalp** [openwisp/openwisp-wifi-login-pages#235]
Implement get a text like translations: right now translations have to be defined in the configuration file of each organization, repeating the same text over and over, we should avoid this and store the translations in a central place;

However, being able to customize the text for each organization is a great feature and should still be possible if needed.

**Comment by nemesisdesign** [comment]
I'd like to ask suggestions from @R9295 with whom I am working on some other project in which we used https://ttag.js.org/ to do this.

Aarnav, here we'll need to do the same thing, with the difference that texts can be overridden by configuration if needed.
If you have any suggestion or recommendation, let us know!

**Comment by R9295** [comment]
Since there is an express backend, you could lazy load the files that ```ttag``` needs (```.po.json```) depending on the locale, which is ideal. I will think a bit more about dynamic po file generation based on the config.

**Comment by nemesisdesign** [comment]
What if we define all strings as placeholders and then have po files for each language, including english?
We could then tweak the code to look for custom po files first, and if the customized versions are found the default po files are ignored.

For example, by default the app would look for:

1. `{languagecode}_custom.po`
2. `{languagecode}.po`

By default option 1 will not be provided, but users of this app can prepare a custom po file with different wording if needed.
That means that by default, option 2 is used.
