### ISSUE TITLE
[component] Design and develop password change component.

### ISSUE THREAD

**Issue by Vivekrajput20** [openwisp/openwisp-wifi-login-pages#32]
Openwisp-radius has a feature to allow users to change the password. The node proxy server already has [controller](https://github.com/openwisp/openwisp-wifi-login-pages/blob/master/server/controllers/password-change-controller.js) to change the password. However, the frontend app does not have a password change component because it was not there in the previous project.
Design and develop the react component to allow users to change the password from the status page.

**Comment by someshkar** [comment]
Hey, do I need to use some existing styling package(like bootstrap) or can I write my own styles with a CSS-in-JS package like styled-components?

**Comment by someshkar** [comment]
Another question, which route should the login page be served on?

**Comment by Vivekrajput20** [comment]
@someshkar we are not using any styling package currently, the captive needs to be very light weight and the app is not that large for now so all the styles are written in CSS only. Since password change is not a very large component, you should also style the component with CSS only.
The password change component will be served on the status page route.

Regards
Vivek

**Comment by someshkar** [comment]
@Vivekrajput20 which file actually handles `GET` routes in the project? I can only see a routes folder in the server directory, which handles the API's `POST` routes.

Regards,
Somesh

**Comment by Vivekrajput20** [comment]
@someshkar the projects has 2 apps. One, a express.js sever to proxy frontend requests to openwisp-radius server. Two, a react app for developing the UI of the frontend app.
[server](https://github.com/openwisp/openwisp-wifi-login-pages/tree/master/server) folder has code of the proxy server and [client](https://github.com/openwisp/openwisp-wifi-login-pages/tree/master/client) is a react app. You will require to setup openwisp-radius locally to work on this issue. 

Regards
Vivek

**Comment by someshkar** [comment]
So I need to set this up? There aren't really any instructions in the readme on that repository.

https://github.com/openwisp/openwisp-radius

Regards,
Somesh

**Comment by AshutoshAgrawal2004** [comment]
Can I work on this task?

Regards,
Ashutosh

**Comment by someshkar** [comment]
Hey! Sorry, I've claimed the task for now, and have started work.

Regards,
Somesh

**Comment by AshutoshAgrawal2004** [comment]
No problem! I will abandon it.

Regards,
Ashutosh
