### ISSUE TITLE
[feature] Add possibility to configure sticky message

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-wifi-login-pages#347]
Add the possibility to configure a sticky message with custom HTML which is shown in all pages.

It can be used for communicating scheduled maintenance operations or any other important message which the provider of the service wants to communicate to their users.

**Comment by codesankalp** [comment]
Can you help me deciding the UI of the sticky message?
Also, Do I have to add an API endpoint for this which will decide whether to show the sticky message or not?

**Comment by nemesisdesign** [comment]
> Can you help me decide the UI of the sticky message?
> I found this:
> ![image](https://user-images.githubusercontent.com/56037184/130039069-c4a8d30c-e1de-403f-a279-81705d97ba89.png)
> 
> Also, Do I have to add an API endpoint for this which will decide whether to show the sticky message or not?
> Reason: As messages can be changed over time for the sticky messages so rebuilding site is not feasible for each change.

For the moment we can add this in the config as for the other custom HTML sections, the idea of allowing to change it dynamically is good, but I believe we should develop a new openwisp module just for this, so users could change also other parts of the config dynamically, we may do this in the future if the usage of this work takes off.

For the position, I think it should be below the main menu and above the main content.
