### ISSUE TITLE
[fix] Username field not updated after changing mobile phone number

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-wifi-login-pages#353]
Right now the username is hidden if it's the same as the username.

But when the phone number is changed, the old username stays.
This patch fixes the backend issue (openwisp-radius) so the username is updated automatically after the phone number is validated: https://github.com/openwisp/openwisp-radius/pull/285.

So I think we have two options:

1. if the registration method is mobile_phone, always hide the username
2. update the username in userData after successful phone number change operation

What do you think is the best thing to do @codesankalp?

**Comment by codesankalp** [comment]
Updating option is more feasible because the username is being used in the captive portal login form.
