### ISSUE TITLE
[change] Create reusable function for errors

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-wifi-login-pages#357]
Right now we are including a lot of code like:

```
{errors.username && (
  <div className="error">
    <span className="icon">!</span>
    <span className="text">{errors.username}</span>
  </div>
)}
``` 

Maybe we can create an utility function (not sure if it's worth it to have another component for this as it will complicate the tree a lot) for this? This would give us the following advantages:

- bring down size a bit (these lines are repated in almost all components)
- make it easy to change the style of errors

I am thinking of something like:

```javascript
fieldError (errors, key) => {
  (
    {errors[key] ? (
      <div className="error">
        <span className="icon">!</span>
        <span className="text">{errors[key]}</span>
      </div>
    ) : ''}
  );
}
```

**Comment by iamvaishnav** [comment]
Can I work on this?

**Comment by nemesisdesign** [comment]
> Can I work on this?

Sure, go ahead :+1:

**Comment by codesankalp** [comment]
Hello @iamvaishnav, Can you proceed with some other issue as this issue needs to be fixed asap?
I would suggest going ahead with https://github.com/openwisp/openwisp-wifi-login-pages/issues/358 issue.

**Comment by iamvaishnav** [comment]
@codesankalp Yeah, sure.

**Comment by nemesisdesign** [comment]
@iamvaishnav take a look at https://github.com/openwisp/openwisp-wifi-login-pages/issues/362, maybe it's something that interests you? Come to the [OpenWISP support chat](https://gitter.im/openwisp/general) if you have any question or to better coordinate with us.
