### ISSUE TITLE
[theme] Change default theme colors to match new OpenWISP admin theme

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-wifi-login-pages#362]
This gray thing is quite sad :joy:.

It would be great to change the default theme colors to match the new OpenWISP admin theme added recently to openwisp-utils master (lighter colors, red links, etc).

This is not urgent but would be great to have it, it would make it look even more professional and coordinated with the rest of OpenWISP.

The screenshots will have to be updated, we can upload those in a separate branch which we use only for screenshots to avoid making master branch too heavy (this is something we're doing in all repos).

**Comment by iamvaishnav** [comment]
I'd like to work on this one. However, I'm not sure how to proceed exactly.

**Comment by nemesisdesign** [comment]
> I'd like to work on this one. However, I'm not sure how to proceed exactly.

See the new theme in action by following these steps: https://github.com/openwisp/openwisp-utils#installing-for-development
Come to https://gitter.im/openwisp/general if you need help.
