### ISSUE TITLE
[docs] Add link to related ansible role

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-wifi-login-pages#364]
We'll have to help users to deploy this app, I am using an ansible role, once this is ready for wider usage we can add a link from the README of this app to it: https://github.com/openwisp/ansible-openwisp-wifi-login-pages/.

**Comment by atharmohammad** [comment]
@nemesisdesign I would like to work on it

**Comment by codesankalp** [comment]
@atharmohammad You can start working.
