### ISSUE TITLE
[bug] User is logged out from status for temporary connection issues

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-wifi-login-pages#394]
While testing I have noticed the user can be logged out while in status if the fetching of the session data fails for some reason.
I think we should log out the user only if the auth token is not valid anymore, any other issue can be ignored because it could be a temporary connection glitch (eg: WiFI may have automatically changed to another network, mobile data connection, the web server may have been reloading in that moment, etc.).

**Comment by codesankalp** [comment]
@nemesisdesign In this, if the session is not fetched then I should also remove the error toast?

**Comment by nemesisdesign** [comment]
> @nemesisdesign In this, if the session is not fetched then I should also remove the error toast?

Yes I think we can log out the user and show the error toast only if the API returns something like 403 or 401, for all other cases we can just fail silently.
