### ISSUE TITLE
[ux] Show error if token validation on openwisp-radius API fails

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-wifi-login-pages#40]
If the token validation of openwisp-radius fails (because organization uuid and secret have not been configured correctly) the operations (login, registration, etc) should fail with an error message.

We should also support the case in which the openwisp-radius API is returning a 500 internal server error or not responding (use mocking to write tests for this case).

PS: it seems that if the openwisp-radius is unavailable, an error message is correctly returned, but if the API is not replying (for example, if you drop an ipdb.set_trace() in the python code, preventing the API to respond) the react app acts like if the API has responded, while it should wait a bit and then timeout.

**Comment by Vivekrajput20** [comment]
This can be accomplished along with [issue/45](https://github.com/openwisp/openwisp-wifi-login-pages/issues/45).

**Comment by nemesisdesign** [comment]
Clarifications: I think that for misconfiguration errors we should show a generic error message in the browser, while the error message displayed in the browser JS console and in the node.js output can be more detailed.

Imagine if this issue happens in production: the user would be confused if we tell them the secret is not configured correctly, they may think it's an issue with their password.

**Comment by nikitaermishin** [comment]
@nemesisdesign And what about token validation? Can we put validation request in `componentDidMount()` (in `registsration`, `login`, e t.c.)? (Now it locates in `status.js`, so it runs only after login success)

**Comment by Vivekrajput20** [comment]
@nemesisdesign  agreed.

**Comment by Vivekrajput20** [comment]
@nikitaermishin they are unprotected routes, we don't require Authorization for accessing those routes, so it's not necessary to validate token on those routes.
