### ISSUE TITLE
Switch from username to email in sign-up and login

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-wifi-login-pages#41]
When signing up, we can sign up users by putting their email as their username, at login they will have to use their email.

This usually results in better user experience.

**Comment by Vivekrajput20** [comment]
@nemesisdesign I think we should change the backend to check for either username or email. And then change the frontend to let user login using email. Setting username as email will end up making this captive portal unusable for existing back end. If we will send emails as username field. Front end validation won't allow existing users with username not as email to make a request.

**Comment by nemesisdesign** [comment]
@Vivekrajput20 I already do this and I have not encountered particular issues, can you provide an example in which this wouldn't work?
We can of course improve the backend too.
