### ISSUE TITLE
[chores:ux] Hide main scrollbar when modals are open

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-wifi-login-pages#459]
While working to fix the modal on old browser I experimented in making it full screen on narrow screens, but it doesn't look great because the main scrollbar shows up. 

I think we can hide the main scrollbar (set `overflow:hidden` to body and html) while the modal is open, as long as these properties are added back when the modal closes.

**Comment by harsh-9in** [comment]
hi @nemesisdesign  can I work on this issue?

**Comment by ManishShah120** [comment]
Yes, @harsh-9in go for it. :+1:

**Comment by nemesisdesign** [comment]
@harsh-9in this issue depends on changes in https://github.com/openwisp/openwisp-wifi-login-pages/pull/457, you need to branch from there.

**Comment by harsh-9in** [comment]
Sure @nemesisdesign
