### ISSUE TITLE
[bug] Change password redirects to payment page

### ISSUE THREAD

**Issue by pandafy** [openwisp/openwisp-wifi-login-pages#494]
**How to replicate**

1. Sign up using credit card method
2. On the `/payment/daft` page, click on change password and change your password.

**Actual Result**
After submitting the form, the page redirects to payment page. 

**Expected Result**

After submitting the form, the page should redirect to `/payment/draft` page.

**Comment by Aryamanz29** [comment]
I give it a try

**Comment by pandafy** [comment]
@Aryamanz29 this is an advanced issue. Kindly consider working on something else. 
Thanks!

**Comment by pandafy** [comment]
This issue was not as advanced as I expected it to be https://github.com/openwisp/openwisp-wifi-login-pages/pull/520/files#diff-850f456c366133ee4bbd9c13f63f9a2c178f23ddb40a8440d4182d1cfda7fe69 😉

**Comment by Aryamanz29** [comment]
> This issue was not as advanced as I expected it to be https://github.com/openwisp/openwisp-wifi-login-pages/pull/520/files#diff-850f456c366133ee4bbd9c13f63f9a2c178f23ddb40a8440d4182d1cfda7fe69 😉 

Same I thought 🙂
