### ISSUE TITLE
[wifi-login-pages] The README should indicate steps required to run this with openwisp-radius

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-wifi-login-pages#57]
The README should indicate steps required to run this with openwisp-radius, at least in development mode.

It should clearly state that this app needs openwisp-radius, link to the project, and explain how to bring it up in a development environment, step by step, eg:

1. install nodejs, npm, yarn

link resources to do this

2. install openwisp-radius

link to documentation of openwisp-radius about installing for development

3. prepare configuration of organization

set openwisp-radius URL
set uuid
set secret

3. run npm install and npm start

4. open login page of recently configured org in the browser

The above is just an example, some steps may be missing. We need to ensure users can easily understand and run this app.

**Comment by iamRishabh07** [comment]
@nemesisdesign  I would like to work on this issue.
