### ISSUE TITLE
[bug] The default org should not show login by username or phone number

### ISSUE THREAD

**Issue by codesankalp** [openwisp/openwisp-wifi-login-pages#589]
~~Currently It is not possible to login by username and phone number with the default org because the input field pattern limits it only for email.~~

~~**Default configuration for login form**:~~

~~https://github.com/openwisp/openwisp-wifi-login-pages/blob/3a179d55779ad98d5fced4ffda49ef5eea51af18/organizations/default/default.yml#L163-L166~~

~~See [username field configuration](https://github.com/openwisp/openwisp-wifi-login-pages#username-field-in-login-form) in README to enable login using username and phone number.~~

As the user gets registered using email so the username by default is email so we should show only email as the label for input username.

**Comment by nemesisdesign** [comment]
I think we could change the default to not mention username, since by default when registering with email the username should be the email if I am not wrong.

**Comment by nemesisdesign** [comment]
PS: this was more a bug than not a change.
