### ISSUE TITLE
[docs] Update README index with missing heading sections

### ISSUE THREAD

**Issue by nemesifier** [openwisp/openwisp-wifi-login-pages#623]
The README misses a few headings in the [Table of contents section](https://github.com/openwisp/openwisp-wifi-login-pages#table-of-contents), let's fix this.
If there's any compatible markdown plugin which automatically generates the table of contents and is compatible with github, let's use that instead.

**Comment by avvicky** [comment]
I'd like to work on it, can i

**Comment by IayushCoderJOD** [comment]
plz assign this issue to me I had started working on it locally @nemesisdesign

**Comment by nemesisdesign** [comment]
There is already an open PR for this issue https://github.com/openwisp/openwisp-wifi-login-pages/pull/624.

**Comment by Flamki** [comment]
@nemesisdesign plz review the branch

**Comment by nemesifier** [comment]
The new docs made this issue obsolete.
