### ISSUE TITLE
[bug] Payment flow get stuck at `/payment/draft` page

### ISSUE THREAD

**Issue by pandafy** [openwisp/openwisp-wifi-login-pages#629]
**Steps to Replicate**

1. Set `payment_requires_internet` to `True` in the organization configuration
2. Sign up using a plan that requires payment 
3. On the `/payment/draft` page, click on `Proceed with the payment` button 

**Expected Outcome**
The app redirects the user to the payment gateway 

**Actual Outcome**
The app redirects user back to the `/payment/draft` page

**Comment by pandafy** [comment]
After debugging, I came to conclusion that this bug was introduced in https://github.com/openwisp/openwisp-wifi-login-pages/pull/520. 

The login and registration pages redirects to `/payment/draft` if the user plan requires payment. The `/payment/draft` page then sets the "Proceed with the payment" button URL using the following logic: 

https://github.com/openwisp/openwisp-wifi-login-pages/blob/3aa77cb81b753ea4c13d413ba432ac294882d232/client/components/payment-status/payment-status.js#L125-L127

If the plan requires payment, the user should be redirected to the `/status` page so the user gets logged into the captive portal. But, in the `/status` page the user gets redirect back to `/payment/process` due to the changes done in #570. 

https://github.com/openwisp/openwisp-wifi-login-pages/blob/3aa77cb81b753ea4c13d413ba432ac294882d232/client/components/status/status.js#L197-L200

**Comment by nemesisdesign** [comment]
We could set a redux state variable or anything like that which indicates that the user has clicked on proceed to payment.
Then the status component should look for this variable and if payment requires internet proceed with the CP login, before doing this though, we could also remove this redux state variable to make sure that if the payment is canceled the user will see the draft page again.
