### ISSUE TITLE
[wifi-login-pages] Add remember me checkbox

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-wifi-login-pages#63]
Add a "remember me" checkbox, enabled by deafult.

If the checkbox is disabled, the app will not store session information in cookies (as it does now by default), but it will use `sessionStorage` as an alternative way to recognize that users have already logged-in (showing them the status page).

This feature is important because public wifi is sometimes used in shared computers in public places, and therefore we may have to disable it by default.

**Comment by yuktibagrodia** [comment]
Can I do it?

**Comment by nemesisdesign** [comment]
@yuktibagrodia are you sure you understand the requirement? It's not just about adding a remember me checkbox but also changing internal functionality. If yes, go ahead.
If not, there are simpler issues to get start contributing.

**Comment by yuktibagrodia** [comment]
I will give it a try. @nemesisdesign

**Comment by ishansinghal9810** [comment]
Is it fixed yet if not i am happy to contrib

**Comment by niteshsinha17** [comment]
@ishansinghal9810 If you are not working on it. I would like take this issue.

**Comment by codesankalp** [comment]
I am working on it.

**Comment by niteshsinha17** [comment]
Actually it was in the backlog so I was waiting 😄 
If you want then no problem you can work.

**Comment by codesankalp** [comment]
Thank You @niteshsinha17.

**Comment by codesankalp** [comment]
Should I add `remember-me` field for the registration part also?
