### ISSUE TITLE
[change] Do not send new SMS unless needed

### ISSUE THREAD

**Issue by nemesifier** [openwisp/openwisp-wifi-login-pages#656]
On some phones, clicking on an SMS to read the verification code will cause the mini-browser to close.
When the user opens the mini-browser again and gets logged in, the verification flow starts again and sends a new SMS, the old one not being valid anymore, this effectively causes the user to not be able to complete the SMS verification from their phone.

We shall modify OWLP and OpenWISP RADIUS to allow finding out if the user already has any valid Phone Token available, if so, we must not send a new code but allow them to use the previous one, they can send a new code if they want using the "resend" button.

This will need us to add another API endpoint which will just return either true or false, true if the user has a valid code, false if they don't. This will require changing OpenWISP RADIUS. We cannot rely on localStorage for this because it's not 100% reliable (some mini-browsers have limited support).

**Comment by pandafy** [comment]
@nemesifier why don't we simple update the `/account/phone/token` view in OpenWISP? 

The `CreatePhoneTokenView` would first query the database if a PhoneToken for the current user with the given details is present. If a PhoneToken is present, it would return HTTP 201 response. If the PhoneToken is not present, it will create the PhoneToken and return HTTP 201 response. 

We can use different HTTP codes (200 and 201 respectively) to show what operation have (or not have) been performed.
