### ISSUE TITLE
[wifi-login-pages] set mac address of the user to sessionStorage

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-wifi-login-pages#66]
The login page should be changed to get the `calling_station_id` (the mac address of the user) querystring parameter and save it to `sessionStorage`.

**Comment by Vivekrajput20** [comment]
@nemesisdesign how to get the `calling_station_id`?

**Comment by nemesisdesign** [comment]
> @nemesisdesign how to get the `calling_station_id`?

It will be sent in the querystring of the URL, eg: `https://loginpage.com/org-name/?calling_station_id=11:22:33:44:55:66`.

Can we make the parameter name customizable by org if needed?
Different captive portals implement this differently and may use a different name for the querystring param.
