### ISSUE TITLE
Wrong api prefix to get access token

### ISSUE THREAD

**Issue by lfdominguez-servinfo** [openwisp/openwisp-wifi-login-pages#695]
I'm trying to use this captive portal page but I getting bad request from the OpenWISP server:

![image](https://github.com/openwisp/openwisp-wifi-login-pages/assets/119055741/fe3a8e81-a982-4d22-962c-948cee6905e8)

Response:
```json
{"detail":"Method \"GET\" not allowed."}
```

I think that the problem is here (missing `/radius/organization`:
https://github.com/openwisp/openwisp-wifi-login-pages/blob/0bbd4261da072b34c5baae045c3dc7b43efc0b10/client/constants/index.js#L1C78-L1C78

Is using an endpoint that I don't found on OpenWISP api docs, only this:
![image](https://github.com/openwisp/openwisp-wifi-login-pages/assets/119055741/458486f3-e13b-43b7-8e2b-ab37523b9cfe)

**Comment by nemesifier** [comment]
Hi, it is not clear to me what you're doing exactly to replicate this problem. Can you please explain what steps and setup you have to incur in this issue? The 405 response from the server doesn't mean the URL is wrong, it means the server doesn't expect a GET request on that URL.

**Comment by lfdominguez-servinfo** [comment]
> Hi, it is not clear to me what you're doing exactly to replicate this problem. Can you please explain what steps and setup you have to incur in this issue? The 405 response from the server doesn't mean the URL is wrong, it means the server doesn't expect a GET request on that URL.

Exacly, here i see two errors:
1 - This is a POST request, why the server respond with "GET" not allowed (GET?)
2 - To replicate this problem i deploy the ansible of openwisp on the server, working OK, then deploy the ansible of openwisp-login-pages, configure a organization and try to login, the error that i see is that one I show here. Then i try to search about the api used on openwisp but i dont found (on all API show by openwisp in `/api/v1/docs/`) one that respond to the request done by login pages (`/api/v1/{slug}/account/token`), only exists that contains that call one with the `/radius/organization/`

**Comment by lfdominguez-servinfo** [comment]
Forget about this... i was thinking that the request was sent to the OpenWISP server and not to the wifi login pages server.
