### ISSUE TITLE
Where is the template config for chilli captive portal configuration

### ISSUE THREAD

**Issue by lfdominguez-servinfo** [openwisp/openwisp-wifi-login-pages#697]
Hi, going to the demo openwrt webpage, one can see that the `Captive Portal` exists there, but how can I get the source of that template. When I go to templates on the controller, the `Captive Portal` one not showing (why?) and on my own Controller, there is nothing about `chilli` package when configuring a captive portal. 
Someone can show a real example of how to configure the captive portal using Chilli with the OpenWISP Controller Templates?

**Comment by nemesifier** [comment]
This is a bug tracker, we use it only to track bugs. Please use the support channels to ask questions.
