### ISSUE TITLE
Setup/Config Help: Sign Up Returns 404

### ISSUE THREAD

**Issue by smcpeck** [openwisp/openwisp-wifi-login-pages#703]
I think I'm close, but I feel like I'm missing something with the initial configuration and having everything linked together.

I've used `ansible` playbooks for installing OpenWisp @ `wifi.mydomain.com` and OpenWisp WiFi Login Pages @ `wifi-login.mydomain.com`.

My RasPi OpenWRT install self-registered with OpenWisp.

I've created an org with `yarn add-org` and linked it to my `default` org in OpenWisp.
`yarn test` succeeds in full.

```
Test Suites: 22 passed, 22 total
Tests:       339 passed, 339 total
Snapshots:   54 passed, 54 total
Time:        15.47 s
```

I've included `openwisp-radius` with my install.
`radtest` "works." (i.e. I get an auth error because no users are setup yet, but it is at least doing its job.)

I'm following this: https://openwisp-radius.readthedocs.io/en/stable/developer/freeradius.html

When I try to signup, attempting to create a RADIUS user, I see the following:

```
POST  https://wifi-login.mydomain.com/api/v1/{orgSlug}/account/
Status 404 Not Found
```

I think I am confused and not setting up the two domains to work with each other properly.

Specifically, I don't have clarity for the following when I'm adding a new org:
```
? What is the captive portal login action URL? 
? What is the captive portal logout action URL?
? What is the URL of OpenWISP RADIUS? 
```

I've been at this for a couple/few days now and scouring different documentation/examples to no avail.
Can anyone show me where I'm going wrong and steer me in the right direction?

Happy to provide more information if I can.

**Comment by nemesifier** [comment]
Sorry for my late response, the fact that you get a request like `https://wifi-login.mydomain.com/api/v1/{orgSlug}/account/` in your request log is weird, it should be something like: `https://wifi-login.mydomain.com/api/v1/org-slug-name/account/`.

**Comment by smcpeck** [comment]
I was simply using that as a placeholder for my actual org-slug.

I've moved on. Using OpenWrt and OpenNDS instead: much simpler. Way too difficult to install/configure this software and the documentation/community is very lacking.
