### ISSUE TITLE
[feature] Allow users to switch plans from the status page

### ISSUE THREAD

**Issue by pandafy** [openwisp/openwisp-wifi-login-pages#736]
Show user's their active plan. 

If the user's plan is expired or exhausted, then show an option to upgrade their plan. 

The upgrade button should only be shown on the upgrade plan. 

When showing plans for upgrade, hide user's current plan from the options. 

If the plan validity is 0 days (unlimited), then do not show days in plan choices. This needs to be done on the registration page as well.

**Comment by bajajtushar094** [comment]
Hi @pandafy, I can work on it. Can you assign it to me?
