### ISSUE TITLE
[change] Outdated Twitter Logo

### ISSUE THREAD

**Issue by AquibKhann** [openwisp/openwisp-wifi-login-pages#743]
The website currently displays an outdated version of the Twitter logo. The logo being used is not in sync with the latest branding guidelines.

Steps to Reproduce:

Visit the website
Navigate to the section displaying social media links.
Observe the Twitter logo and compare it with the latest Twitter branding guidelines.
Expected Result:
The Twitter logo should adhere to the most recent branding guidelines provided by Twitter.

Actual Result:
The current Twitter logo appears to be outdated and may not align with the latest branding standards.

https://github.com/openwisp/openwisp-wifi-login-pages/assets/120818337/56128ad6-d5ff-4847-bef6-5ab2f5b57e8e

**Comment by d1vyanshu-kumar** [comment]
please assign this issue to me.
