### ISSUE TITLE
[wifi-login-pages] Bug: fonts get blocked by captive portal

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-wifi-login-pages#79]
We should not load fonts from the google fonts API: https://fonts.googleapis.com/css?family=Montserrat:500,600&display=swap.

This request gets blocked by the captive portal and fails.
Fonts should be shipped from the static files of the application.

**Comment by iamhitman21** [comment]
May I work on this issue?

**Comment by nemesisdesign** [comment]
@iamhitman21 go for it
