### ISSUE TITLE
[wifi-login-pages] Add server side logging (nodejs)

### ISSUE THREAD

**Issue by Vivekrajput20** [openwisp/openwisp-wifi-login-pages#82]
Add a proper logger to the server implementation.
Log HTTP requests to openwisp-radius with INFO.
When there is an error, ensure the logging works also if the request is canceled (eg: timeout). Right now in case of timeout the request logging fails and there's no logging.

**Comment by sujaykundu777** [comment]
@Vivekrajput20 Added this #86 PR

**Comment by ishansinghal9810** [comment]
Is there something that i can do

**Comment by codesankalp** [comment]
I am working on this.
